Feature/cp2 back button on demoextras
ipol-journal/ipolDevel pull request #139
Opened 2022-11-29 12:00 UTC by hmaciasc

CP Feature requested:
- Back button on demoextras page
- Upload button disabled when no file selected
- Warning message on user email in use

2022-11-29 12:21 UTC, mcolom approved these changes

2022-11-29 20:10 UTC, kidanger requested changes

2022-11-29 20:10 UTC, kidanger commented on cp2/ControlPanel/templates/demoExtras.html
> +                filename = filename;
remove else branch

2022-11-30 09:01 UTC, Jyotsnarajan approved these changes

2022-11-30 09:23 UTC, hmaciasc commented on cp2/ControlPanel/templates/demoExtras.html
> +                filename = filename;
Done, sorry that slipped out

2022-11-30 09:25 UTC, kidanger approved these changes

2022-11-30 09:27 UTC, merged