Feature/demoextras drag and drop
ipol-journal/ipolDevel pull request #143
Opened 2023-01-02 11:21 UTC by hmaciasc

2023-01-03 18:56 UTC, kidanger requested changes

2023-01-03 18:56 UTC, kidanger commented on cp2/ControlPanel/templates/demoExtras.html
> +            <input type="hidden" name="title" value="{{ title }}">
I don't think title is required here?

2023-01-03 18:56 UTC, kidanger commented on cp2/ControlPanel/static_cp/js/demoExtras.js
> +                formData.append('title', urlParams.get('title'))
I think think title is required here

2023-01-05 17:52 UTC, kidanger requested changes
Can you rebase into one or two commits? (in particular we should not unnecessary merge commits)

2023-01-06 08:57 UTC, mcolom reviewed
The code is quite clear.

I have just a question before accepting the PR.
In the HTML we have <input type="hidden" name="demo_id" value="{{ demo_id }}", which is posted to {% url 'add_extras' %}.

Is it possible for a user to simply spoof a different value for demo_id and overwrite the extras of a non-owned demo?

2023-01-06 10:29 UTC, kidanger approved these changes

2023-01-06 10:45 UTC, mcolom approved these changes
Answer from Héctor: the backend checks that you're only changing your own demos.

2023-01-06 10:49 UTC, Jyotsnarajan approved these changes

2023-01-06 11:30 UTC, merged