Blobs internal error fixed
ipol-journal/ipolDevel pull request #158
Opened 2023-03-15 06:03 UTC by Jyotsnarajan

2023-03-15 10:44 UTC, hmaciasc requested changes
I would also add a fix in editBlobForm.html. I forgot to set the _type_ to the input to "number" in **line 23**. That way it would prevent from even writing anything other than numbers inside the input. Perhaps also add a minimum html value of 0.

2023-03-16 07:30 UTC, mcolom commented
I'm accepting the PR, with the condition that you fulfill Héctor's requests.

2023-03-16 07:33 UTC, mcolom approved these changes
Accepted.
Remember to add Héctor's requests.
Just a minor change: instead of "new_pos_set cannot be non-interger" write "new_pos_set needs to be an integer".

2023-03-16 20:04 UTC, kidanger approved these changes

2023-03-17 09:14 UTC, merged