[CP/fix] user email sync with demoinfo db
ipol-journal/ipolDevel pull request #165
Opened 2023-04-04 11:45 UTC by hmaciasc

Since as of now demoinfo returns OK but no information in some cases due to mismatch between CP database and demoinfo database concerning editors I've changed it so if no editor is returned it will asume editors will be added to demoinfo if the email is not in there yet.

It is a small change but wanted to make everyone review instead of just commit it.

2023-04-04 12:39 UTC, mcolom requested changes
Thanks for the fix.
Before accepting, I have one request and some questions.
Request: add some comments to facilitate understanding what the code does. Explain which is the email contained in instance, in old_editor and in editor (or editor_exists).

Then it'd be good to comment what we intend at each of the IF branches.
if old_editor_exists and not editor_exists --> Here I guess it means we have an email in demoInfo, but the new one doesn't exist. Then there's no clash and we update.
elif not old_editor_exists and not editor_exists --> The editor doesn't have an email and there isn't anyone else with that email. In that case we use the email from CP (instance).
Else: --> Otherwise it's an error because we're trying to assign an existing the email, so it's an error.

Well, I think these explanations (or the ones you think are accurate if these are not) should be added as comments.

The case that motivated this fix, it was having an empty email from a new user. It should go to "elif not old_editor_exists and not editor_exists" and it'll assign a None to the email. If I understood correctly, this is what is intended.

If you add these few explanation comments and confirm that everything is fine (specially the case of "no email in the CP with new user", I'll accept the PR quickly.

2023-04-04 18:44 UTC, kidanger approved these changes

2023-04-05 07:50 UTC, hmaciasc commented
> The case that motivated this fix, it was having an empty email from a new user. It should go to "elif not old_editor_exists and not editor_exists" and it'll assign a None to the email. If I understood correctly, this is what is intended.
Can't reply to your message @mcolom so I'll quote. It will assign None to the email in that signal and won't send anything to demoinfo since demoinfo can't save an editor with no email which is a DISTINCT field on the DB. It will only add_editor when we have an email and that email is not in use. If we find old_email in demoinfo and new email is different then we update editor in demoinfo.
If somehow (errors or manual changes) an editor is not updated in demoinfo while being updated on CP it will probably create problems in the future but those cases should be very rare. Until we remove one of the DBs, django or demoinfo editor we will keep having such problems, hopefully less and less with this fix.

2023-04-05 07:56 UTC, mcolom commented
> > The case that motivated this fix, it was having an empty email from a new user. It should go to "elif not old_editor_exists and not editor_exists" and it'll assign a None to the email. If I understood correctly, this is what is intended.
> > Can't reply to your message @mcolom so I'll quote. It will assign None to the email in that signal and won't send anything to demoinfo since demoinfo can't save an editor with no email which is a DISTINCT field on the DB. It will only add_editor when we have an email and that email is not in use. If we find old_email in demoinfo and new email is different then we update editor in demoinfo.
> > If somehow (errors or manual changes) an editor is not updated in demoinfo while being updated on CP it will probably create problems in the future but those cases should be very rare. Until we remove one of the DBs, django or demoinfo editor we will keep having such problems, hopefully less and less with this fix.

Ok, thanks for the explanation! And for adding the comments in the code also.

2023-04-05 07:57 UTC, mcolom approved these changes

2023-04-05 08:09 UTC, Jyotsnarajan approved these changes

2023-04-05 09:16 UTC, merged