Refactor/merge archive into core
ipol-journal/ipolDevel pull request #196
Opened 2023-11-23 16:19 UTC by hmaciasc

This PR moves and merges archive into core simplifying our sysadmin tasks.
Before pushing to prod:
- Move DB file outside of archive and into core DB folder
- Renaming static_file folders into:
- [ ] staticData/archive_blobs/
- [ ] staticData/archive_thumbs/
- Reinstall core packages once merged

2023-11-27 08:57 UTC, kidanger requested changes

2023-11-27 08:57 UTC, kidanger commented on ipol_demo/modules/core/archive/archive.py
> +
Missing a return for the error case. Used here https://github.com/ipol-journal/ipolDevel/pull/196/files#diff-67df7a992db8fdc8199e09bd24943d112592476d57ef394361ea29df5057fc60R223

2023-11-27 08:57 UTC, kidanger commented on ipol_demo/modules/core/archive/archive.py
> +                    settings.database_dir + "/drop_create_db_schema.sql", "r"
```suggestion
               curdir = os.path.dirname(__file__)
                with open(
                    os.path.join(curdir, "drop_create_db_schema.sql"), "r"
```
(same as in demoinfo)
and remove the `database_dir` entry from the settings

2023-11-27 08:57 UTC, kidanger commented on ipol_demo/modules/core/config.py
> +    blobs_thumbs_dir: str = "staticData/archive_thumbs/"
can we prefix these with `archive_`? otherwise it will clash with the blobs module.

2023-11-27 10:22 UTC, kidanger approved these changes

2023-11-27 10:36 UTC, mcolom reviewed
No major comments on this PR, it looks good.
I have just two questions before accepting:
It seems that the static data from the Archive now will be in the Core's directory.
		- alias  /home/ipol/ipolDevel/ipol_demo/modules/archive/staticData/;
		+ alias  /home/ipol/ipolDevel/ipol_demo/modules/core/staticData/;
However, even if now you're importing Archive as a Core's component, still I think this static data should be in the Archive's directory for a better organization.

- You changed  BASE_URL = os.environ["IPOL_URL"] to BASE_URL = os.environ.get("IPOL_URL"). I'm curious to know why. Is it because one raises and exception and the other returns None, or something like that?

2023-11-27 15:13 UTC, mcolom approved these changes
OK, thanks for your answer!

2023-11-28 13:31 UTC, Jyotsnarajan approved these changes

2023-11-28 14:38 UTC, merged