[Tools/DDL] added code to update a DDL
ipol-journal/ipolDevel pull request #208
Opened 2024-09-17 09:29 UTC by Jyotsnarajan

2024-09-17 10:32 UTC, hmaciasc approved these changes

2024-09-19 14:06 UTC, kidanger requested changes

2024-09-19 14:06 UTC, kidanger commented on tools/DDL/ddl.py
> +                ddl['build']['url'] = f"git@github.com:ipol-journal/{editorsdemoid}.git"
Maybe check that the previous url was what we expected (git@github.com:mlbriefs/demoid.git), so that we don't override other demos.

2024-09-19 14:06 UTC, kidanger commented on tools/DDL/ddl.py
> +elif command == "update":
```suggestion
elif command == "update_git_url":
```

2024-09-20 06:49 UTC, kidanger approved these changes

2024-09-20 06:53 UTC, merged